export { StyledWrapper } from './StyledWrapper';
export { StyledDetails } from './StyledDetails';
export { StyledImage } from './StyledImage';
export { StyledImageWrapper } from './StyledImageWrapper';
export { StyledInfoWrapper } from './StyledInfoWrapper';
export { StyledInfo } from './StyledInfo';
export { StyledRealName } from './StyledRealName';
export { StyledDetailsTop } from './StyledDetailsTop';
export { StyledAdditionalPicturesWrapper } from './StyledAdditionalPicturesWrapper';
